#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CountMeIn.Resource", IsApplication=true)]

namespace CountMeIn
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int planets_array = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060000
			public const int theme_devicedefault_background = 2131099648;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int border_shadow = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int button_round = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ButtonSignInStyle = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ButtonSignUpStyle = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Calendar = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int calendar3 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int clock2 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int clock3 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int createEvebts = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int EditTextBorder = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int @event = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int group2 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int Icon = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int invite = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int logo = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int logo3 = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int ProgressBarStyle = 2130837520;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f08003a
			public const int addVenue = 2131230778;
			
			// aapt resource value: 0x7f08002a
			public const int btnLogIn = 2131230762;
			
			// aapt resource value: 0x7f08002c
			public const int btnSignIn = 2131230764;
			
			// aapt resource value: 0x7f08000b
			public const int btnSignUp = 2131230731;
			
			// aapt resource value: 0x7f080015
			public const int closeTime = 2131230741;
			
			// aapt resource value: 0x7f080016
			public const int createEvent = 2131230742;
			
			// aapt resource value: 0x7f080033
			public const int createEventButton = 2131230771;
			
			// aapt resource value: 0x7f08001a
			public const int createGroup = 2131230746;
			
			// aapt resource value: 0x7f080032
			public const int createGroupButton = 2131230770;
			
			// aapt resource value: 0x7f08001e
			public const int createInvite = 2131230750;
			
			// aapt resource value: 0x7f080006
			public const int createVenue = 2131230726;
			
			// aapt resource value: 0x7f080014
			public const int dateClose = 2131230740;
			
			// aapt resource value: 0x7f08002e
			public const int datePicker1 = 2131230766;
			
			// aapt resource value: 0x7f080004
			public const int editText1 = 2131230724;
			
			// aapt resource value: 0x7f08000c
			public const int eventButton = 2131230732;
			
			// aapt resource value: 0x7f080012
			public const int eventButton2 = 2131230738;
			
			// aapt resource value: 0x7f080010
			public const int eventDate = 2131230736;
			
			// aapt resource value: 0x7f08000e
			public const int eventDate1 = 2131230734;
			
			// aapt resource value: 0x7f08001f
			public const int eventDateView = 2131230751;
			
			// aapt resource value: 0x7f08003b
			public const int eventListView = 2131230779;
			
			// aapt resource value: 0x7f080020
			public const int eventNameView = 2131230752;
			
			// aapt resource value: 0x7f080011
			public const int eventTime = 2131230737;
			
			// aapt resource value: 0x7f08000f
			public const int eventTime1 = 2131230735;
			
			// aapt resource value: 0x7f080021
			public const int groupNameView = 2131230753;
			
			// aapt resource value: 0x7f08001d
			public const int guestListView = 2131230749;
			
			// aapt resource value: 0x7f080034
			public const int logOut = 2131230772;
			
			// aapt resource value: 0x7f080029
			public const int loginPassword = 2131230761;
			
			// aapt resource value: 0x7f080028
			public const int loginUserName = 2131230760;
			
			// aapt resource value: 0x7f080027
			public const int logoImageView = 2131230759;
			
			// aapt resource value: 0x7f080035
			public const int mainScrollView = 2131230773;
			
			// aapt resource value: 0x7f080036
			public const int pendingEventListView = 2131230774;
			
			// aapt resource value: 0x7f080031
			public const int pendingInviteButton = 2131230769;
			
			// aapt resource value: 0x7f080008
			public const int phoneNo = 2131230728;
			
			// aapt resource value: 0x7f080000
			public const int relativeLayout1 = 2131230720;
			
			// aapt resource value: 0x7f08000a
			public const int renterPwd = 2131230730;
			
			// aapt resource value: 0x7f08001c
			public const int sendInvite = 2131230748;
			
			// aapt resource value: 0x7f080026
			public const int spinner = 2131230758;
			
			// aapt resource value: 0x7f080017
			public const int textDate = 2131230743;
			
			// aapt resource value: 0x7f080023
			public const int textDate1 = 2131230755;
			
			// aapt resource value: 0x7f080002
			public const int textEnterVenueName = 2131230722;
			
			// aapt resource value: 0x7f080019
			public const int textLabel = 2131230745;
			
			// aapt resource value: 0x7f080009
			public const int textPassword = 2131230729;
			
			// aapt resource value: 0x7f080018
			public const int textTime = 2131230744;
			
			// aapt resource value: 0x7f080024
			public const int textTime1 = 2131230756;
			
			// aapt resource value: 0x7f08001b
			public const int textVenue = 2131230747;
			
			// aapt resource value: 0x7f080003
			public const int textVenueAddress = 2131230723;
			
			// aapt resource value: 0x7f080001
			public const int textVenueName = 2131230721;
			
			// aapt resource value: 0x7f080005
			public const int textVenuePhone = 2131230725;
			
			// aapt resource value: 0x7f08000d
			public const int timeButton = 2131230733;
			
			// aapt resource value: 0x7f080013
			public const int timeButton2 = 2131230739;
			
			// aapt resource value: 0x7f08002f
			public const int timePicker1 = 2131230767;
			
			// aapt resource value: 0x7f080022
			public const int timeView = 2131230754;
			
			// aapt resource value: 0x7f08002b
			public const int txtCreateAccount = 2131230763;
			
			// aapt resource value: 0x7f080038
			public const int txtEventDate = 2131230776;
			
			// aapt resource value: 0x7f080037
			public const int txtEventDate1 = 2131230775;
			
			// aapt resource value: 0x7f080025
			public const int txtEventName = 2131230757;
			
			// aapt resource value: 0x7f080039
			public const int txtEventName1 = 2131230777;
			
			// aapt resource value: 0x7f08002d
			public const int txtOr = 2131230765;
			
			// aapt resource value: 0x7f080030
			public const int upcomingeventButton = 2131230768;
			
			// aapt resource value: 0x7f080007
			public const int username = 2131230727;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AddVenue = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CreateAccount = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int CreateEvent = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int CreateGroup = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int EventDetails = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int GroupDetails = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int GuestInvite = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int GuestInviteRow = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int InviteGuests = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int Login = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int LoginSignUP = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int Main = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int MainMenu = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int PendingEventRow = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int PendingEventView = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int PendingInvites = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int Test = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int TestCreateEvent = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int TestingMainMenu = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int UpComingEvent = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int UpComingEventRowView = 2130903060;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040005
			public const int add_password_hint = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int add_reenter_password_hint = 2130968582;
			
			// aapt resource value: 0x7f040003
			public const int add_username1_hint = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int add_username2_hint = 2130968580;
			
			// aapt resource value: 0x7f040002
			public const int add_username_hint = 2130968578;
			
			// aapt resource value: 0x7f040007
			public const int planet_prompt = 2130968583;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int Theme_Custom = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
